import { bigserial, index, jsonb, numeric, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { merchants } from './merchants.js';

export const metricEvents = pgTable(
  'metric_events',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    merchantId: text('merchant_id')
      .notNull()
      .references(() => merchants.id, { onDelete: 'cascade' }),
    metricName: text('metric_name').notNull(),
    value: numeric('value').notNull().default('1'),
    tags: jsonb('tags').$type<Record<string, string | number | boolean>>(),
    ts: timestamp('ts', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    merchantMetricTsIdx: index('metric_events_merchant_metric_ts_idx').on(
      t.merchantId,
      t.metricName,
      t.ts.desc(),
    ),
  }),
);

export type MetricEvent = typeof metricEvents.$inferSelect;

export const metricNames = {
  selectorFirstTrySuccess: 'selector.first_try.success',
  selectorFirstTryFail: 'selector.first_try.fail',
  selectorHealAttempted: 'selector.heal.attempted',
  selectorHealSucceeded: 'selector.heal.succeeded',
  selectorOverrideSkipped: 'selector.override.skipped',
  selectorOverrideAlerted: 'selector.override.alerted',
  toolCallDurationMs: 'tool.call.duration_ms',
  voiceNumericPriceCorrected: 'voice.numeric_price_corrected',
  installReceived: 'install.received',
  installRateLimited: 'install.rate_limited',
  installRejectedOrigin: 'install.rejected_origin',
  installRejectedDomain: 'install.rejected_domain',
  onboardingSafetyCleared: 'onboarding.safety.cleared',
  onboardingSafetyRejected: 'onboarding.safety.rejected',
  onboardingSafetyError: 'onboarding.safety.error',
  onboardingFingerprintShopify: 'onboarding.fingerprint.shopify',
  onboardingFingerprintWoocommerce: 'onboarding.fingerprint.woocommerce',
  onboardingFingerprintCustom: 'onboarding.fingerprint.custom',
  onboardingFingerprintFetchFailed: 'onboarding.fingerprint.fetch_failed',
  onboardingCompleted: 'onboarding.completed',
  onboardingFailed: 'onboarding.failed',
  onboardingCatalogSyncStarted: 'onboarding.catalog_sync.started',
  onboardingCatalogSyncCompleted: 'onboarding.catalog_sync.completed',
  onboardingCatalogSyncDegraded: 'onboarding.catalog_sync.degraded',
  onboardingCatalogSyncFailed: 'onboarding.catalog_sync.failed',
  onboardingSelectorExtractStarted: 'onboarding.selector_extract.started',
  onboardingSelectorExtractCompleted: 'onboarding.selector_extract.completed',
  onboardingSelectorExtractFailed: 'onboarding.selector_extract.failed',
  onboardingSmokeStarted: 'onboarding.smoke.started',
  onboardingSmokePassed: 'onboarding.smoke.passed',
  onboardingSmokeFailed: 'onboarding.smoke.failed',
  onboardingDetectedPlatformDegraded: 'onboarding.detected_platform.degraded',
  onboardingFingerprintMagentoDetected: 'onboarding.fingerprint.magento_detected',
  onboardingFingerprintBigcommerceDetected: 'onboarding.fingerprint.bigcommerce_detected',
  onboardingFingerprintWixDetected: 'onboarding.fingerprint.wix_detected',
  onboardingFingerprintSquarespaceDetected: 'onboarding.fingerprint.squarespace_detected',
  domAction: 'dom.action',
  domActionFailed: 'dom.action.failed',
  selectorResolverHit: 'selector.resolver.hit',
  selectorResolverMiss: 'selector.resolver.miss',
  selectorResolverHealed: 'selector.resolver.healed',
  selectorResolverGaveUp: 'selector.resolver.gave_up',
  selectorOverrideFailing: 'selector.override.failing',
  domAdapterDegradedToSuggest: 'dom.adapter.degraded_to_suggest',
  domSessionActionCap: 'dom.session.action_cap',
  suggestMessageSent: 'suggest.message.sent',
  suggestProductCardSent: 'suggest.product_card.sent',
  suggestCartGetEmpty: 'suggest.cart_get.empty',
  adapterPromotedToSuggest: 'adapter.promoted_to_suggest',
  agentTurnStarted: 'agent.turn.started',
  agentTurnCompleted: 'agent.turn.completed',
  agentToolInvoked: 'agent.tool.invoked',
  agentToolRetryExhausted: 'agent.tool.retry_exhausted',
  agentSayPriceStripped: 'agent.say.price_stripped',
  agentCapHit: 'agent.cap.hit',
  agentSessionClosed: 'agent.session.closed',
  agentSonnetError: 'agent.sonnet.error',
  conversionIngested: 'conversion.ingested',
  conversionMissNoVisitor: 'conversion.miss.no_visitor_in_window',
  conversionMissNoRecommendation: 'conversion.miss.no_recommendation_match',
  conversionMissMerchantUnknown: 'conversion.miss.merchant_unknown',
  conversionMissAuthFailed: 'conversion.miss.auth_failed',
  conversionMissDuplicate: 'conversion.miss.duplicate',
} as const;
