export const STRINGS = {
  trayConnected: 'CONNECTED',
  trayOffline: 'OFFLINE',
  micStart: 'Start voice call',
  micMute: 'Mute mic',
  micUnmute: 'Unmute mic',
  endCallAria: 'End call',
  closeAria: 'Close',
  openAria: 'Open shoppingmate',
  panelHelpHeading: "Hi, I'm",
  panelHelpSubtitle: "I'm here to help you:",
  panelBullets: [
    'Find the right product fast',
    'Compare options out loud',
    'Check out without leaving the page',
  ] as readonly string[],
  poweredBy: 'Powered by shoppingmate',
  chatPlaceholder: 'Type a quick question…',
  reconnecting: 'Reconnecting…',
  disconnected: 'Connection lost — reload to retry',
  closed: {
    user: 'Conversation ended',
    cap: 'Time to wrap up — reload for a new chat',
    error: 'Something went wrong',
  },
  payNow: 'Pay now →',
  capWarning: 'A couple minutes left',
  thinking: 'thinking…',
  micDenied: 'Mic blocked — switching to text',
} as const;
