export const STRINGS = {
  pillCallable: 'Talk to Sage',
  pillTextOnly: 'Chat with Sage',
  pillCollapsed: 'Sage',
  callBtn: 'CALL',
  callBtnEnd: 'END',
  chatBtnAria: 'Open text chat',
  callBtnAria: 'Start voice call',
  endCallAria: 'End call',
  closeAria: 'Close',
  callHeaderSpeaking: 'speaking',
  callHeaderListening: 'listening',
  chatHeaderSubtitle: 'text fallback · voice preferred',
  chatPlaceholder: 'Type a quick question…',
  chatGreeting: "Hi, I'm Sage. What are you shopping for today?",
  reconnecting: 'Reconnecting…',
  disconnected: 'Connection lost — reload to retry',
  closed: {
    user: 'Conversation ended',
    cap: 'Time to wrap up — reload for a new chat',
    error: 'Something went wrong',
  },
  payNow: 'Pay now →',
  capWarning: 'A couple minutes left',
  thinking: 'Sage is thinking…',
  micDenied: 'Mic blocked — switching to text',
} as const;
